version: '3'
services:
  postgres:
    image: "postgres:15"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aewo
      PGDATA: ./var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./db/clickhouse:/var/lib/clickhouse

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: aewo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped